# .github/workflows/notify-api-on-issue.yml

name: Notify API on Issue Created

on:
  issues:
    types:
      - opened

jobs:
  notify-api:
    runs-on: ubuntu-latest

    steps:
      - name: Get JWT Token
        id: auth
        run: |
          TOKEN=$(curl -s -X POST "https://avaapi-fch5a5ayf5c5dta4.canadacentral-01.azurewebsites.net/api/v1/auth/login" \
            -H "accept: application/json" \
            -H "Content-Type: application/json" \
            -d '{
              "username":"'"${{ secrets.API_USERNAME }}"'",
              "password":"'"${{ secrets.API_PASSWORD }}"'"
            }' | jq -r '.access_token')

          echo "TOKEN=$TOKEN"
          echo "token=$TOKEN" >> $GITHUB_OUTPUT

      - name: Send Labels to API
        run: |
          curl -X PATCH "https://avaapi-fch5a5ayf5c5dta4.canadacentral-01.azurewebsites.net/api/v1/data/tickets/${{ github.event.issue.number }}/labels" \
            -H "accept: application/json" \
            -H "Content-Type: application/json" \
            -H "Authorization: Bearer ${{ steps.auth.outputs.token }}" \
            -d '{
              "labels": ["Bug"]
            }'
